1

In [2]:
import numpy as np
import torch

In [3]:
a = np.array([1,2,3,4,5,6,7,8])
new_a = a.reshape(2, 4)

print(new_a)

[[1 2 3 4]
 [5 6 7 8]]


2

In [4]:
a = torch.tensor([1, 3, 5, 6])
b = torch.tensor([5, 6, 8, 9])

def addition(x, y):
    return torch.add(x, y)

print(addition(a, b))

def multiplication(x, y):
    return torch.mul(x, y)

print(multiplication(a, b))

def exponent(x, y):
    return torch.pow(x, y)

print(exponent(a, b))

def dot_product(x, y):
    return torch.dot(x, y)

print(dot_product(a, b))

def exponent(x):
    return torch.exp(x)

print(exponent(a))
print(exponent(b))

def logarithm(x):
    return torch.log(x)

print(logarithm(a))
print(logarithm(b))

def both(x):
    x = torch.exp(x)
    return torch.log(x)

print(both(a))
print(both(b))

tensor([ 6,  9, 13, 15])
tensor([ 5, 18, 40, 54])
tensor([       1,      729,   390625, 10077696])
tensor(117)
tensor([  2.7183,  20.0855, 148.4132, 403.4288])
tensor([ 148.4132,  403.4288, 2980.9580, 8103.0840])
tensor([0.0000, 1.0986, 1.6094, 1.7918])
tensor([1.6094, 1.7918, 2.0794, 2.1972])
tensor([1.0000, 3.0000, 5.0000, 6.0000])
tensor([5., 6., 8., 9.])


3a

In [5]:
point = torch.tensor([5.0, 6.0, 8.0, 9.0], requires_grad = True)
coeffs = torch.tensor([1.0, 3.0, 5.0, 6.0])

def g(p):
    return torch.sum(coeffs * torch.exp(p) * p**2)

function_values = g(point)
function_values.backward()
gradient = point.grad
print(gradient)

tensor([   5194.4609,   58093.7500, 1192383.2500, 4813232.0000])


3b

In [6]:
A = torch.tensor([[4.0, 3.0], [7.0, 9.0]], requires_grad = True)

B = torch.tensor([[3.0, 5.0], [1.0, 11.0]])

inside = A.T @ A @ B.T @ A @ A.T @ A @ B
f = torch.log(torch.norm(inside, p=2)**2)

print(f)

tensor(34.8454, grad_fn=<LogBackward0>)


3c

In [7]:
point = torch.tensor([3.0, 7.0], requires_grad = True)

values = torch.sum(torch.tanh(point))
values.backward()
gradient = point.grad
print(gradient)

tensor([9.8660e-03, 3.3379e-06])


4

In [8]:
import torch

a = torch.tensor([1, 2, 3])
print(a)

b = a.numpy()
print(b)

print(a.float())

tensor([1, 2, 3])
[1 2 3]
tensor([1., 2., 3.])


5

In [9]:
import numpy as np
from numpy import linalg as LA

x = np.array([[1, 3, 5], [2, 1, 5]])
y = np.array([[8, 4], [3, 6], [2, 7]])

print(x @ y)

frob = np.array([100, 2, 1])
print(LA.norm(frob.reshape(1, 3), 'fro'))

[[27 57]
 [29 49]]
100.024996875781
